### PR TITLE
Fix and test for ambiguities on 0.6

### LINKED ISSUE #2: Is it possible to specify the rounding mode? (Also - display error in Julia 0.6)
```
julia> a = RInt(7.2)
Error showing value of type RoundingIntegers.RInt64:
ERROR: MethodError: convert(::Type{Unsigned}, ::RoundingIntegers.RUInt64) is ambiguous. Candidates:
  convert(::Type{T}, x::Union{RoundingIntegers.RSigned, RoundingIntegers.RUnsigned}) where T<:Number in RoundingIntegers at /Users/seth/.julia/v0.6/RoundingIntegers/src/RoundingIntegers.jl:103
  convert(::Type{T}, x::T) where T in Base at essentials.jl:29
Stacktrace:
 [1] dec(::RoundingIntegers.RUInt64, ::Int64, ::Bool) at ./intfuncs.jl:426
 [2] show(::IOContext{Base.Terminals.TTYTerminal}, ::RoundingIntegers.RInt64) at ./show.jl:259
 [3] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::RoundingIntegers.RInt64) at ./REPL.jl:122
 [4] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::RoundingIntegers.RInt64) at ./REPL.jl:125
 [5] display(::RoundingIntegers.RInt64) at ./multimedia.jl:194
```

Also, I can do this with regular `round`:
```
julia> round(7.8, RoundDown)
7.0
```
but I don't quite know how to specify the rounding strategy for `RInt`.

### PR DESCRIPTION
**Pull request by timholy**
Fixes #2 

Might fail tests if `nightly` isn't new enough, but it passes locally.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

File: test/runtests.jl [hunk 1]
```diff
@@ -1,7 +1,13 @@
...
-
-@test isempty(detect_ambiguities(Base, Core, RoundingIntegers))
+if VERSION < v"0.6.0-pre.alpha.229"
+    using RoundingIntegers
+    @test isempty(detect_ambiguities(Base, Core, RoundingIntegers))
+else
+    ambs0 = detect_ambiguities(Base, Core, Compat)
+    using RoundingIntegers
+    ambs1 = detect_ambiguities(Base, Core, Compat, RoundingIntegers)
+    @test isempty(setdiff(ambs1, ambs0))
```
Comment (tkelman) [inline test/runtests.jl:9]: does Base have new ambiguities that it didn't before alpha.229, or does Compat?

Comment (timholy) [reply test/runtests.jl:9]: Still has the 2 `cat` ambiguities. Compat doesn't add any, but I wanted to be conservative since there's no reason to fail here due to issues with other packages.

Comment (tkelman) [reply test/runtests.jl:9]: then what's the significance of alpha.229 ? was that the new defaulting to not counting `Union{}` ?

Comment (timholy) [reply test/runtests.jl:9]: That's when @StefanKarpinski revamped the `detect_ambiguities` API.
